# This is a basic workflow to help you get started with Actions

name: Pure-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: ModuleFast
        # You may pin to the exact commit or the version.
        # uses: JustinGrote/ModuleFast-action@93f08c7ec999b7892f0ce66a5ecace5cf7a9cfd0
        uses: JustinGrote/ModuleFast-action@v0.0.1
        with:
          # The modules to install. Separate module specifications with a space or linebreak. If this setting is not specified, will look for a required modules spec in the working directory.
          specification: PowerShellNotebook
        
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
  
      - name: 'Run Azure CLI commands'
        shell: pwsh
        run: |
          az account show
          (az group list) | convertfrom-json | ft name, location
          get-command az | format-list

      # Runs a set of commands using the runners shell
      - name: Invoke PowerShell Notebook
        shell: pwsh
        run: |
          Invoke-PowerShellNotebook ./tester-notebook.ipynb
